myapp/urls.py
from django.urls import path, include
from . import views

app_name = "myapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
]

story4/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace="story4")),
    path('', include('story6.urls', namespace="story6")),
]

story7/status/urls.py
from django.urls import path
from . import views

app_name = "status"

urlpatterns = [
    path('story6',views.index, name='index'),
]

myapp/models.py
from django.db import models

# Create your models here.

story7/status/models.py
from django.db import models

# Create your models here.
class StatusPost(models.Model):
	status = models.CharField(max_length=300)
	date = models.DateTimeField(auto_now_add=True)

story7/status/forms.py
from django import forms
from status.models import StatusPost

class StatusForm(forms.ModelForm):
	status = forms.CharField(label='Status ', widget=forms.Textarea(attrs={'class': 'textarea'}))

	class Meta:
		model = StatusPost
		fields = {'status'}

myapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'index.html')

def home(request):
	return render(request, 'home.html')

def about(request):
	response = {'':''}
	return render(request, 'about.html')

def gallery(request):
	response = {'':''}
	return render(request, 'gallery.html')

def contact(request):
	response = {'':''}
	return render(request, 'contact.html')

story7/status/views.py
# Create your views here.

myapp/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="bodyC" style="background-image: url('{% static 'img/g.png' %}');">
	

	<article>
	<div class="clearfix">
	  <div class="box" style="background-color:none">
	  </div>
	  <div class="box" style="background-color:none">
	  <h1 style="font-size:5vw; color: white">ABOUT</h1>
	  <p style="font-size:1vw; color: white">Hello! I’m Mauludi, from Faculty of Computer Science, Universitas Indonesia.

	I love books! I always try to make a good book last but I’m a buggar for ‘just one more chapter’ before I know it it’s done. I’m also passionately on learning PHP programming, as well as Linux-based System.</p>
	  </div>
	</article>

</div>

{% endblock %}

myapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Me</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Righteous&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">


</head>
<body>
{% include "navbar.html" %}

{% block content %}

{% endblock %}
</body>
</html>

myapp/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<body bgcolor="black">
	
<article>
	<div class="clearfix">
	  <h1 style="font-size:5vw; color: white">CONTACT</h1>
	  <p style="font-size:2vw; color: white">stay in touch with me!</p><br>
	  <p>
			<a href="mailto:ladymauludi@gmail.com"><img src="{% static 'img/mail.png' %}" alt="gmail" width="100" height="100"></a>

			<a href="https://id.linkedin.com/in/mauludi-afina-mirza-299826129"><img src="{% static 'img/in.png' %}" alt="linkedin" width="100" height="100"></a>
	  </p>
	  </div>
</article>

{% endblock %}

myapp/templates/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<body bgcolor="black">
	<div class="container text-center">

<h1> Click Me </h1>
<!-- Large modal -->
<button class="btn btn-default" data-toggle="modal" data-target=".bs-example-modal-lg">click to view gallery</button>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
     <img class="img-responsive" src="{% static 'img/3.jpg' %}" alt="lake">
      <div class="carousel-caption">
        Lake
      </div>
    </div>
    <div class="item">
      <img class="img-responsive" src="{% static 'img/2.jpg' %}" alt="mountain">
      <div class="carousel-caption">
        Mountain
      </div>
    </div>
     <div class="item">
      <img class="img-responsive" src="{% static 'img/3.jpg' %}" alt="hill">
      <div class="carousel-caption">
        Hill
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
    </div>
  </div>
</div>
</div>

{% endblock %}

myapp/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<body class="bodyB" style="background-image: url('{% static 'img/bb.png' %}');"></body>
	

{% endblock %}

myapp/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Me</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Righteous&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
<style>
.button {
  border-radius: 4px;
  background-color: purple;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 28px;
  padding: 20px;
  width: 200px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}
</style>
</head>
<body bgcolor="black">
	

</body>
<center><button class="button"><a href="home"><span>Great Things Inside</span></a></button></center>
</html>

myapp/templates/navbar.html
{% load static %}

{% block content %}

<div class="topnav" id="myTopnav">
	  <a href="{% url 'story4:contact' %}">CONTACT</a>
	  <a href="{% url 'story4:gallery' %}">GALLERY</a>
	  <a href="{% url 'story4:about' %}">ABOUT</a>
	  <a href="{% url 'story4:home' %}" class="active">HOME</a>
	  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
	    <i class="fa fa-bars"></i>
	  </a>
	</div>
	<script>
	function myFunction() {
	  var x = document.getElementById("myTopnav");
	  if (x.className === "topnav") {
	    x.className += " responsive";
	  } else {
	    x.className = "topnav";
	  }
	}
	</script>

{% endblock %}